"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.3
    Generated by: https://openapi-generator.tech
"""


import unittest

import WardleyCrewAPI
from WardleyCrewAPI.api.wardley_maps_online_api import WardleyMapsOnlineApi  # noqa: E501


class TestWardleyMapsOnlineApi(unittest.TestCase):
    """WardleyMapsOnlineApi unit test stubs"""

    def setUp(self):
        self.api = WardleyMapsOnlineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_wardley_data_v2_maps_fetch_get(self):
        """Test case for fetch_wardley_data_v2_maps_fetch_get

        Fetch Wardley Data  # noqa: E501
        """
        pass

    def test_get_image_v2_image_filename_get(self):
        """Test case for get_image_v2_image_filename_get

        Get Image  # noqa: E501
        """
        pass

    def test_save_wardley_map_v2_maps_save_post(self):
        """Test case for save_wardley_map_v2_maps_save_post

        Save Wardley Map  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
