"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.component_request import ComponentRequest


class TestComponentRequest(unittest.TestCase):
    """ComponentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponentRequest(self):
        """Test ComponentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ComponentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
