"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import WardleyCrewAPI
from WardleyCrewAPI.model.owm_text_request import OwmTextRequest


class TestOwmTextRequest(unittest.TestCase):
    """OwmTextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwmTextRequest(self):
        """Test OwmTextRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OwmTextRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
