"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.map_id_request import MapIdRequest


class TestMapIdRequest(unittest.TestCase):
    """MapIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMapIdRequest(self):
        """Test MapIdRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MapIdRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
