"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.3
    Generated by: https://openapi-generator.tech
"""


import unittest

import WardleyCrewAPI
from WardleyCrewAPI.api.conversions_api import ConversionsApi  # noqa: E501


class TestConversionsApi(unittest.TestCase):
    """ConversionsApi unit test stubs"""

    def setUp(self):
        self.api = ConversionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_id2_png_v2_convertid2png_post(self):
        """Test case for convert_id2_png_v2_convertid2png_post

        Convert Id 2 Png  # noqa: E501
        """
        pass

    def test_convert_owm2_json_v2_convertowm2json_post(self):
        """Test case for convert_owm2_json_v2_convertowm2json_post

        Convert Owm 2 Json  # noqa: E501
        """
        pass

    def test_convert_owm2_png_v2_convertowm2png_post(self):
        """Test case for convert_owm2_png_v2_convertowm2png_post

        Convert Owm 2 Png  # noqa: E501
        """
        pass

    def test_convert_owm2_svg_v2_convertowm2svg_post(self):
        """Test case for convert_owm2_svg_v2_convertowm2svg_post

        Convert Owm 2 Svg  # noqa: E501
        """
        pass

    def test_convert_owm2_toml_v2_convertowm2toml_post(self):
        """Test case for convert_owm2_toml_v2_convertowm2toml_post

        Convert Owm 2 Toml  # noqa: E501
        """
        pass

    def test_convert_owm2_yaml_v2_convertowm2yaml_post(self):
        """Test case for convert_owm2_yaml_v2_convertowm2yaml_post

        Convert Owm 2 Yaml  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
