"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import WardleyCrewAPI
from WardleyCrewAPI.model.text_request import TextRequest


class TestTextRequest(unittest.TestCase):
    """TextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextRequest(self):
        """Test TextRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
