"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.3
    Generated by: https://openapi-generator.tech
"""


import unittest

import WardleyCrewAPI
from WardleyCrewAPI.api.tools_api import ToolsApi  # noqa: E501


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self):
        self.api = ToolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_github_map_v2_get_github_map_get(self):
        """Test case for get_github_map_v2_get_github_map_get

        Get Github Map  # noqa: E501
        """
        pass

    def test_list_github_maps_v2_list_github_maps_get(self):
        """Test case for list_github_maps_v2_list_github_maps_get

        List Github Maps  # noqa: E501
        """
        pass

    def test_open_map_v2_openmap_get(self):
        """Test case for open_map_v2_openmap_get

        Open Map  # noqa: E501
        """
        pass

    def test_privacy_statement_v2_privacy_get(self):
        """Test case for privacy_statement_v2_privacy_get

        Privacy Statement  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
