"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import WardleyCrewAPI
from WardleyCrewAPI.model.map_text_and_warnings import MapTextAndWarnings


class TestMapTextAndWarnings(unittest.TestCase):
    """MapTextAndWarnings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMapTextAndWarnings(self):
        """Test MapTextAndWarnings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MapTextAndWarnings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
