"""
    Wardley Mapping Crew API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.3
    Generated by: https://openapi-generator.tech
"""


import unittest

import WardleyCrewAPI
from WardleyCrewAPI.api.open_wardley_maps_api import OpenWardleyMapsApi  # noqa: E501


class TestOpenWardleyMapsApi(unittest.TestCase):
    """OpenWardleyMapsApi unit test stubs"""

    def setUp(self):
        self.api = OpenWardleyMapsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_map_from_id_v2_generate_mapfromid_post(self):
        """Test case for generate_map_from_id_v2_generate_mapfromid_post

        Generate Map From Id  # noqa: E501
        """
        pass

    def test_generate_map_from_text_v2_generate_mapfromtext_post(self):
        """Test case for generate_map_from_text_v2_generate_mapfromtext_post

        Generate Map From Text  # noqa: E501
        """
        pass

    def test_generate_svg_map_v2_generate_svgmap_post(self):
        """Test case for generate_svg_map_v2_generate_svgmap_post

        Generate Svg Map  # noqa: E501
        """
        pass

    def test_get_owm_anchors_v2_get_owm_anchors_post(self):
        """Test case for get_owm_anchors_v2_get_owm_anchors_post

        Get Owm Anchors  # noqa: E501
        """
        pass

    def test_get_owm_annotations_v2_get_owm_annotations_post(self):
        """Test case for get_owm_annotations_v2_get_owm_annotations_post

        Get Owm Annotations  # noqa: E501
        """
        pass

    def test_get_owm_component_v2_get_owm_component_post(self):
        """Test case for get_owm_component_v2_get_owm_component_post

        Get Owm Component  # noqa: E501
        """
        pass

    def test_get_owm_components_v2_get_owm_components_post(self):
        """Test case for get_owm_components_v2_get_owm_components_post

        Get Owm Components  # noqa: E501
        """
        pass

    def test_get_owm_map_text_v2_get_owm_text_post(self):
        """Test case for get_owm_map_text_v2_get_owm_text_post

        Get Owm Map Text  # noqa: E501
        """
        pass

    def test_get_owm_notes_v2_get_owm_notes_post(self):
        """Test case for get_owm_notes_v2_get_owm_notes_post

        Get Owm Notes  # noqa: E501
        """
        pass

    def test_get_owm_pipelines_v2_get_owm_pipelines_post(self):
        """Test case for get_owm_pipelines_v2_get_owm_pipelines_post

        Get Owm Pipelines  # noqa: E501
        """
        pass

    def test_get_owm_warnings_v2_get_owm_warnings_post(self):
        """Test case for get_owm_warnings_v2_get_owm_warnings_post

        Get Owm Warnings  # noqa: E501
        """
        pass

    def test_search_owm_components_v2_search_owm_components_post(self):
        """Test case for search_owm_components_v2_search_owm_components_post

        Search Owm Components  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
